
terraform state rm module.project_sc_diagrams_com.module.dev_env_diagrams_com.module.nextjs_lambda.module.cloudfront.aws_s3_bucket.bucket
terraform state rm module.project_schematical_com.module.prod_env_schematical_com.module.nextjs_lambda.module.cloudfront.aws_s3_bucket.bucket
terraform state rm module.project_schematical_com.module.prod_env_schematical_com.module.cloudfront.aws_s3_bucket.bucket
terraform state rm module.project_schematical_com.module.prod_env_schematical_com.module.cloudfront.aws_s3_bucket.bucket