te+6rraform state rm module.project_schematical_com.aws_route53_record.schematical-com-a
# terraform state rm module.project_schematical_com.aws_route53_record.schematical-com-ns
terraform state rm module.project_schematical_com.aws_route53_record.schematical-com-mx
terraform state rm module.project_schematical_com.aws_route53_zone.schematical_com
terraform state rm module.project_schematical_com.aws_ses_domain_identity.ses_domain_identity